# KallistiOS ##version##
#
# arch/dreamcast/math/Makefile
# (c)2001 Dan Potter
#

# Dreamcast-specific math functions

OBJS = fmath.o matrix.o matrix3d.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab


