# KallistiOS ##version##
#
# thread/Makefile
# (c)2001 Dan Potter
#

OBJS =  sem.o cond.o mutex.o genwait.o
OBJS += thread.o rwsem.o recursive_lock.o once.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



