# KallistiOS ##version##
#
# kernel/fs/Makefile
# (c)2000-2001 Dan Potter
#

OBJS = fs.o fs_romdisk.o fs_ramdisk.o fs_pty.o
OBJS += fs_utils.o elf.o fs_socket.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab

