# libkosext2fs Makefile
# This one is for building everything except the VFS glue outside of KOS.

OBJS = ext2fs.o bitops.o block.o inode.o superblock.o symlink.o directory.o

# Make sure everything compiles nice and cleanly (or not at all).
CFLAGS += -W -pedantic -Werror -std=gnu99 -DEXT2_NOT_IN_KOS -g

libkosext2fs.a: $(OBJS)
	$(AR) rcs $@ $^

clean:
	-rm -f $(OBJS)
	-rm -f libkosext2fs.a
