# KallistiOS ##version##
#
# arch/dreamcast/navi/Makefile
# (c)2002 Dan Potter
#

# IDE
OBJS += navi_ide.o

# Flash BIOS
OBJS += navi_flash.o

# SUBDIRS = fs
SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



