# KallistiOS ##version##
#
# net/Makefile
# (c)2002 Dan Potter
#

OBJS  = net_core.o net_arp.o net_input.o net_icmp.o net_ipv4.o net_udp.o 
OBJS += net_dhcp.o net_ipv4_frag.o net_thd.o net_ipv6.o net_icmp6.o net_crc.o
OBJS += net_ndp.o net_multicast.o net_tcp.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



