# KallistiOS ##version##
#
# net/Makefile
# (c)2002 Dan Potter
#

OBJS =  net_core.o net_arp.o net_input.o net_icmp.o net_ipv4.o net_udp.o net_dhcp.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



