# KallistiOS ##version##
#
# arch/dreamcast/fs/Makefile
# (c)2001 Dan Potter
#

# Dreamcast-specific file systems

OBJS  = fs_iso9660.o fs_vmu.o fs_dcload.o dcload-syscall.o vmufs.o \
 fs_dclsocket.o
# OBJS += fs_dclnative.o dcload-commands.o dcload-net.o dcload-packet.o dcload-syscalls.o
SUBDIRS = 

include $(KOS_BASE)/Makefile.prefab



