# KallistiOS ##version##
#
# arch/dreamcast/hardware/network/Makefile
# (c)2000-2001 Dan Potter
#

# Various network devices
OBJS = broadband_adapter.o lan_adapter.o

SUBDIRS =

include $(KOS_BASE)/Makefile.prefab



