# KallistiOS ##version##
#
# examples/dreamcast/basic/threading/Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.1 2002/04/19 07:53:52 bardtx Exp $

all:
	$(KOS_MAKE) -C general
	$(KOS_MAKE) -C rwsem

clean:
	$(KOS_MAKE) -C general clean
	$(KOS_MAKE) -C rwsem clean
		
dist:
	$(KOS_MAKE) -C general dist
	$(KOS_MAKE) -C rwsem dist


